export {SubcategoryPage} from './SubcategoryPage';
export {MainPage} from './MainPage';
export {CatalogPage} from './CatalogPage';
export {SearchResultPage} from './SearchResultPage';
export {CategoryPage} from './CategoryPage';
export {ProductPage} from './ProductPage';
export {BasketPage} from './BasketPage';
export {OrderFormPage} from "./OrderFormPage"
export {ConfirmationPage} from "./ConfirmationPage"